export const tutorial = [
    'Ah, the new employee. Glad to have you aboard!##We just reached a galaxy full of shiny moons. Moons that must be destroyed!',
    'We’ll start you on a simple moon. We don’t want you scared away on your first day, eh?##The Moonerator has limited shots so choose your shots wisely.',
]

export const story = [
    'Ah, the smell of your first moon destruction. Congrats!##Don’t worry, there’s more where that came from. We’ll warp you to the next moon when you’re ready.',
    'I used to be in your chair. Well, not that exact chair, of course. But I was tasked with destruction sequence finding.##There’s something satisfying about the click of a perfect sequence.',
    'If you grow tired of my babbling, you can disable it.##Although it is nice to talk to someone again. It grows lonely out here amongst the stars.',
    'You’re probably wondering about the destruction sequence.##The colors indicate geological networks in the moon’s interior. The Moonerator Mark v.2.9 works best with limited shots.',
    'My story? Are we friends now? Weird.##Well, I am the designer of the Moonerator. She runS smoothly, doesn’t she? Wasn’t always that way.',
    'No, I wasn’t hired like you. That’s just silly. Professor Destruction, they called me, the destroyer of orbs!##Okay, nobody actually called me that. But they could have.',
    'It’s not like I hate rocks. And I do ensure that there’s nothing living on these moons.##I’m not a monster. At least not anymore.',
    'We have always been in the business of destruction. The Moonerator is the culmination of that journey.##It’s my greatest legacy.',
    'Who funds us? You’re a curious one, aren’t you?##Once we discovered warp engines, you would think that money would stop being a thing.',
    'We had abundant resources and energy that could be used for any purpose.##It’s shocking, I know, but even with free energy and uncountable resources, money was still a thing.',
    'It turns out that it wasn’t the money that people craved, but power. And if everyone had infinite money, then nobody would have power.##Certain dreams turn out to be just that: dreams.',
    'People still use money and therefore they need jobs.##I don’t need to tell you this since you’re here clicking away, earning those credits, right?',
    'My purpose here? Well it’s our purpose really. It’s the destruction of moons.##It’s simple, pure, and it’s a goal you can get behind.',
    'There’s not always an answer to the why question, so you can stop pestering me.##Just know that you’re a small cog in a large machine with a pure purpose. That’s got to provide job satisfaction, right?',
    'I didn’t always destroy moons, of course. In the beginning, well, we started with a different aim. We were making things better.##Isn’t that how it always starts?',
    'This was before you were born during the planet wars.##Warp had just been invented and while there were unlimited planets and systems to explore, some were more important than others.',
    'It was the crossroad systems that mattered.##When you control where warps exit then you profit from any trade that passes through.',
    'I was drafted into the war efforts to control those points.##I had a certain knack for destruction. I have other abilities, of course. But those in power were not interested in those abilities.',
    'The wars were brutal. Destruction was constant.##The destruction sequence to destroy planets is the same as for moons. People and their cities have no impact on the sequences.',
    'As quickly as humans expanded across galaxies, wars were only a step behind.##In those years, I spent all my time warping between systems and promoting the cause of . . . peace.',
    'Peace is a funny word. The powerful seek it once they have power, but the weak avoid it until they have taken that power. And afterwards they too seek . . . peace.',
    'You’re really getting a hang of these sequences. I had my doubts when you first started.##I’ll talk to my boss to see what we can do about your holiday bonus.',
    'There were pockets of peace, of course. When powerful empires rose and controlled vast stretches of galaxies.##But they never lasted. Space is too big to govern effectively, and people are too greedy.',
    'Don’t they teach you anything in those space schools?##Warping is what made these wonders possible. It was the bridge to the stars for humanity.',
    'Warping is like a series of well-planned highways.##They’re fast but you still need to pass between adjacent exits to reach distant parts.',
    'And it’s those adjacent exits where there can be trouble.##When there’s trouble in one exit then the following exits become unreachable. And there’s power in trouble.',
    'Troubles created wars and wars created troubles. It’s a cycle.##I think it’s something innate in humans. They start the troubles so that they have something to fix.',
    'Yeah, you would think that weapons would grow more destructive during the wars.##But like most things, there’s a limit.',
    'I mean, sure, I could destroy entire stars but what’s the point?##And black holes would be fun to destroy but physics just won’t let us.',
    'Now, black holes, those are energy generators. Harvesting energy from them was key to the early empires.',
    'You haven’t heard about the black-hole empires? How quickly history is forgotten.##I can’t blame them. Human history is long and sad.',
    'That not repeating history thing? Yeah, that’s only in storybooks.##History has a shape and it’s a repetitive shape. Given a long enough sequence, it will repeat in terrible ways.',
    'Pessimist? Me? I brought you onboard, so that must show I have hope, right?##I can’t change the shape of history, but I can make parts of it more tolerable.',
    'Wow, that was a particularly challenging sequence. Bravo!##Destroying moons sends a message to the system inhabitants. It’s known in the military arts as the projection of power.',
    'There are vast swaths of humanity that are cut off from the rest of us. I think it’s for the best.##But we occasionally run into them when building new warp ways.',
    'They’re not always friendly, of course. And we sometimes run across entire civilizations that didn’t make it.##If we arrive early enough then we can find their remains.',
    'There was a time I thought things would be different. It was early in my planet-busting career.##Her name was General Xin and I ran across her in Sector 781A2.',
    'General Xin made me think that there could be something there, you know?##A multigalaxy-wide coalition trying to make things better for everyone.',
    'It was her charm that threw me off. She shone brighter than entire systems, and when she brought that to bear on you . . . even I was susceptible to it.',
    'At first peace and prosperity seemed inevitable. We stampeded through systems, conquering, and establishing fair governments.',
    'Our campaign was met with little effective resistance, and the people seemed happy to have a strong, charismatic leader.',
    'But the more systems she conquered, the more power she craved, and the more ruthless she became.##She squeezed her systems to fund the conquering of new systems.',
    'Eventually she paid the ultimate price for the squeezing. Oranges only have so much liquid before they’re only pulp.',
    'After she lost control, I wandered the galaxies for a while. I was lost in the fall of her empire and nobody was looking for me.',
    'The chaos closed most traffic on the warp ways. Except for me, of course.##I had an early version of the Moonerator, and you see what it does if there’s trouble.',
    'I would project power but did not use it to conquer. Only to explore.##And it was through that exploration that I came up with my plan.',
    'You’re a part of that plan, you know. You may think your job is only a way to put bread on your family’s table, but to me it’s much more.',
    'You’re the face of the next generation of peace. Peace always has a cost. I tried to mitigate the cost and the cheapest price I could find was the moons.',
    'You and the other destruction sequence technicians project our power and keep the systems in line.##There is no person or government in charge anymore.',
    'There are only the seemingly random movements of the fleet of Moonerators.##Cause trouble and moons explode in your system.',
    'Don’t cause trouble, and the moons still occasionally explode.##Power must be exercised, or it loses its, well, its power.',
    'What results is not the utopia that General Xin dreamed about.##Instead, it’s a steady governance where power and fear are meted out in proportions.',
    'There are well-governed systems, and disastrous ones. Our fleet does not interfere as much as I would like it to.##Our role is to maintain the peace between systems.',
    'I have been around for hundreds of millennia. And this was the most perfect system I can come up with.##It’s a terrible system and people still suffer.',
    'But like democracy, as terrible as this is, the alternative is much worse.##Now, enough jabbering. Keep pounding out those destruction sequences.##Your talkative friend and employer,# A.I. 34C1-98A.',
]

export const endScreen = [
    'Thank you for playing Shoot the Moon (like literally) developed for Github Game Off 2020!##To see the source code and check out my other games, please visit my website at: https://yopeyopey.com/##-David Figatner',
]